panic

diff --git a/bin/dev b/bin/dev
--- a/bin/dev
+++ b/bin/dev
@@ -9,17 +9,21 @@ set -o pipefail
 # set -e : exit the script if any statement returns a non-true return value
 set -o errexit
 
+# Run level: 0: Local, 1: Specifies nodes, 2: Specifies group 3: All nodes
+declare -g glb_run_level=0 glb_run_sudo=0 glb_run_daemon=0
+declare -g glb_file glb_func glb_user
+
 # For option arguments
-declare -Ag opa_rem opa_als opa_fun
+declare -Ag opa_rem opa_als
+
+# The sudo prefix
+[ "$(whoami)" != "root" ] && declare -gr glb_sudo="sudo" || declare -gr glb_sudo=""
 
 #
 # Useage information.
 #
 dev_help_useage() {
-    declare files="<cmd-file>"
-    [ ! -z "$1" ] && files="$1"
-
-    echo "Usage: dev [options] $files <cmd-function> [cmd-arguments]"; echo
+    echo "Usage: dev [options] [project] <cmd-file> <cmd-function> [cmd-arguments]"; echo
 }
 
 #
@@ -59,7 +63,7 @@ dev_help_functions() {
 
     for i in $(compgen -A function); do
         if [[ "${i:0:4}" == "cmd_" ]]; then
-            echo -e "  ${i:4} \t in $glb_wkdir/cmd/$glb_cmd_file:$i()"
+            echo -e "  ${i:4} \t in $glb_wkdir/cmd/$glb_file:$i()"
         fi
     done
 
@@ -77,25 +81,6 @@ dev_cmd_files() {
             ret="$ret $2${i:0:-4}"
         fi
     done
-}
-
-#
-# Init a global constaiont
-# Useage:
-#     dev_const <name> <config-value> <default-value>
-#
-dev_const() {
-    declare varname="glb_$1"
-    [ -z "$2" ] && declare -gr "$varname=$3" || declare -gr "$varname=$2"
-}
-
-#
-# Useage:
-#     dev_wkdir <dev-path>
-#
-dev_wkdir() {
-    declare base="$1" && [ -L "$base" ] && base=$(readlink -f "$base")
-    declare -gr glb_base="$(dirname $(dirname $(realpath $base)))"
 }
 
 #
@@ -130,94 +115,74 @@ dev_dnf() {
 
 #
 # Useage:
-#     dev_conf $@
+#     dev_base <dev-path>
 #
-dev_conf() {
-    # Include configuration files
-    declare cfg
-    for cfg in "$HOME/.dev.conf", "$glb_base/etc/dev.conf"; do
+dev_base() {
+    declare base="$0" cfg;
+    [ -L "$base" ] && base=$(readlink -f $base); base=$(dirname $(realpath $base))
+    if [ "$(basename $base)" == "bin" ]; then
+        declare -gr glb_base="$(dirname $base)"
+    else
+        declare -gr glb_base="$base"
+    fi
+
+    for cfg in "$glb_base/dev.conf",  "$HOME/.dev.conf", "$glb_base/etc/dev.conf"; do
         [ -f $cfg ] && . $cfg && break
     done
 
-    # Support multiple projects.
-    if [ $# -ge 1 ] && [ -n "${cfg_projects[$1]+1}" ]; then
-        declare -gr glb_prj="$1"
-        declare -gr glb_wkdir=${cfg_projects[$1]}
-        return 0
-    else
-        declare -gr glb_prj="dev"
-        declare -gr glb_wkdir=$glb_base
-        return 1
-    fi
+    # Private key: glb_ssh_key
+    [ -z "$cfg_ssh_key" ] && declare -gr glb_ssh_key="$HOME/.ssh/id_rsa" || \
+        declare -gr glb_ssh_key="$HOME/.ssh/$cfg_ssh_key"
 }
 
 #
-# Global variables
 # Useage:
-#     dev_global <base-dir>
+#     dev_project <prj>
 #
-dev_global() {
-    # The sudo prefix
-    [ "$(whoami)" != "root" ] && declare -gr glb_sudo="sudo" || declare -gr glb_sudo=""
-
-    # Private key: glb_ssh_key
-    dev_const "ssh_key" "$HOME/.ssh/$cfg_ssh_key" "$HOME/.ssh/id_rsa"
-
-    # 0: Local machine, 1: Specifies nodes, 2: Specifies group 3: All nodes
-    declare -g glb_run=1 glb_run_level=0 glb_run_sudo=0 glb_run_daemon=0
-
-    # Command file
-    declare -g glb_cmd_file
+dev_prj() {
+    if [ $# -ge 1 ] && [ -n "${cfg_projects[$1]+1}" ]; then
+        declare -gr glb_prj="$1" glb_wkdir=${cfg_projects[$1]}; return 0
+    else
+        declare -gr glb_prj="dev" glb_wkdir=$glb_base; return 1
+    fi
 }
 
 #
 # Prepare command files
 # Useage:
-#     dev_load_files <cmd-file>
+#     dev_cmd <cmd-file>
 #
-dev_load_files() {
-    [[ $# -lt 1 || -z "$1" ]] && return 0 || glb_cmd_file="$1"
-    [ ! -f $glb_wkdir/cmd/$1.cmd ] && return 0
+dev_cmd() {
+    if [[ $# -le 0 || -z "$1" ]]; then
+        dev_help_useage >&2; dev_help_options >&2; dev_help_files >&2; return 1
+    fi
 
-    # Include arguments
+    [ -f $glb_wkdir/lib/bootstrap ] && . $glb_wkdir/lib/bootstrap
     [ -f $glb_wkdir/etc/cmd/$1.conf ] && . $glb_wkdir/etc/cmd/$1.conf
-
-    # Include variables
     [ -f $glb_wkdir/cmd/$1.var ] && . $glb_wkdir/cmd/$1.var
+    if [ ! -f $glb_wkdir/cmd/$1.cmd ]; then
+        echo "Command file not found: $glb_wkdir/cmd/$1.cmd" >&2; return 1
+    fi
 
-    # Include command file
     . $glb_wkdir/cmd/$1.cmd
+    if [[ $# -eq 1 || -z "$2" ]]; then
+        echo "Missing command function" >&2; echo >&2; dev_help_functions >&2; return 1
+    fi
+
+    glb_file="$1"; glb_func="$1"; return 0
 }
 
 #
 # Execute the command
 # Useage:
-#     dev_run_std <cmd-file> <cmd-function> [cmd-arguments]
+#     dev_run <cmd-file> <cmd-function> [cmd-arguments]
 #
 dev_run() {
-    # Execute the command
-    if [[ $# -le 0 || -z "$1" ]]; then
-        echo "dev-err: missing <cmd-file>" >&2
-        echo "" >&2
-        dev_help_useage >&2
-        dev_help_options >&2
-        dev_help_files >&2
-        return 1
-    elif [[ $# -eq 1 || -z "$2" ]]; then
-        echo "dev-err: missing <cmd-function>" >&2
-        echo "" >&2
-        dev_help_useage "$1" >&2
-        # dev_help_options
-        dev_help_functions >&2
-        return 1
-    fi
-
     declare cmd="" fun=${2/-/_}
 
-    [ "${fun:0:4}" == "cmd_" ] || fun="cmd_$fun"
+    [[ "${fun:0:4}" == "cmd_" ]] || fun="cmd_$fun"
     if [[ "$(declare -F $fun)" != "$fun" ]]; then
-        echo "dev: command not found: $fun" >&2
-        return 1
+        echo "dev: command not found: $fun" >&2; return 1
     fi
 
     if [[ $glb_run_level -eq 0 ]]; then
@@ -231,23 +196,19 @@ dev_run() {
         :
     elif [[ $glb_run_level -eq 3 ]]; then
         # Run in all nodes
-        cmd="dev_exec_remote $glb_base/bin/dev"
-        $cmd $@
+        cmd="dev_exec_remote $glb_base/bin/dev"; $cmd $@
     else
-        echo "dev: run level error: $glb_run_level" >&2
-        return 1
+        echo "dev: run level error: $glb_run_level" >&2; return 1
     fi
 }
 
 #
-# Execute a command from all nodes.
 # Useage:
 #     dev_exec_remote dev [options] <cmd-file> <cmd-function> [cmd-arguments]
 #
 dev_exec_remote() {
     if [[ "${#cfg_nodes[@]}" -le 0 ]]; then
-        echo "dev: empty nodes" >&2
-        return 1
+        echo "dev: empty nodes" >&2; return 1
     fi
 
     declare cmd user host
@@ -270,16 +231,10 @@ dev_exec_remote() {
 #     dev_exec_local <command> <arguments>...
 #
 dev_exec_local() {
-    declare host="127.0.0.1"
-    declare user="$(whoami)"
+    declare user="$(whoami)" host="127.0.0.1"
 
     if [[ $glb_run_sudo -eq 1 ]]; then
-        unset opa_fun[sudo]
-        declare cmd="sudo $glb_base/bin/dev"
-        for opt in "${!opa_fun[@]}"; do
-            cmd="$cmd --$opt ${opa_fun[$opt]}"
-        done
-        dev_exec $host $user $cmd -- $glb_cmd_file $@
+        dev_exec $host $user sudo $glb_base/bin/dev $glb_file $@
     else
         dev_exec $host $user $@
     fi
@@ -303,20 +258,16 @@ dev_exec() {
 
     chmod a+wx $log_out $log_err
 
-    # $@ 2>&1 | tee $log_out
-    # ($@ | tee $log_out) 3>&1 1>&2 2>&3 | tee $log_err
     if [[ $glb_run_daemon -eq 1 ]]; then
         cmd="nohup $@ >>$log_out 2>>$log_err &"
-        echo "$cmd" && echo "$cmd" >> $log_out && echo "$cmd" >>$log_err
-        $cmd
+        echo "$cmd" && echo "$cmd" >> $log_out && echo "$cmd" >>$log_err; $cmd
 
         echo "PID: $!"
         # echo "out: $(< $log_out)"
         # echo "err: $(< $log_err)"
     else
         cmd="$@"
-        echo "$cmd" && echo "$cmd" >> $log_out && echo "$cmd" >>$log_err
-        $cmd
+        echo "$cmd" && echo "$cmd" >> $log_out && echo "$cmd" >>$log_err; $cmd
 
         # echo "$?"
     fi
@@ -328,14 +279,13 @@ dev_exec() {
 # a call to main: dev_main "$@"
 #
 dev_main() {
-    . $glb_base/lib/options
-    [ -f $glb_wkdir/lib/bootstrap ] && . $glb_wkdir/lib/bootstrap
+    [ -f $glb_base/lib/options ] && . $glb_base/lib/options
 
     declare opt arg
 
-    # Prepare optional arguments
+    # Optional arguments
     while true ; do
-        if [[ "$1" == "--" ]]; then
+        if [[ "$1" == "--" || "$1" == "-" ]]; then
             shift; break
         elif [[ "${1:0:2}" == "--" ]]; then
             opt="${1:2}"; shift
@@ -350,35 +300,16 @@ dev_main() {
 
         if [[ "$(expr index $opt '=')" -ge 1 ]]; then
             IFS='=' read -ra arg <<< "$opt"
-            opa_fun[${arg[0]}]="${arg[1]}"
+            opa_fun_${arg[0]/-/_} "${arg[1]}"
         elif [[ ! -z "$1" && "${1:0:1}" != "-" ]]; then
-            opa_fun[$opt]="$1"; shift
+            opa_fun_${opt/-/_} "$1" || shift
         else
-            opa_fun[$opt]=""
+            opa_fun_${opt/-/_}
         fi
     done
 
-    # Prepare files
-    dev_load_files $@
-
-    # Do optional functions
-    for opt in "${!opa_fun[@]}"; do
-        opa_fun_${opt/-/_} "${opa_fun[$opt]}"
-    done
-
-    # Do command function
-    [ $glb_run -ne 1 ] && return 0
-
-    if [[ $# -ge 1 && -z $glb_cmd_file ]]; then
-        echo "dev: command file not found: $glb_wkdir/cmd/$glb_cmd_file.cmd" >&2
-        return 1
-    fi
-
-    [ "$(declare -F btp_main)" == "btp_main" ] && btp_main $@
-    dev_run $@
+    dev_prj $@ && shift; dev_cmd $@ || return 1; shift; shift; dev_run $@
 }
 
 # Call to main function. custom function declare before here.
-dev_wkdir $0
-dev_conf $@ && shift
-dev_global && dev_main $@
+dev_base; dev_main $@
diff --git a/lib/options b/lib/options
--- a/lib/options
+++ b/lib/options
@@ -10,17 +10,7 @@
 opa_rem[help]="Help topic and usage information"
 opa_als[h]="help"
 opa_fun_help() {
-    glb_run=0
-
-    if [[ $# -le 0 || -z "$1" ]]; then
-        dev_help_useage
-        dev_help_options
-        dev_help_files
-    else
-        dev_help_useage "$1"
-        dev_help_options
-        dev_help_functions
-    fi
+    dev_help_useage; dev_help_options; dev_help_files; return 0
 }
 
 #
@@ -30,7 +20,8 @@ opa_fun_help() {
 opa_rem[projects]="List all of the available projects"
 opa_als[projects]="projects"
 opa_fun_projects() {
-    :
+    return 0
+    # FIXME
 }
 
 #
@@ -40,55 +31,48 @@ opa_fun_projects() {
 opa_rem[options]="List all optional arguments"
 opa_als[options]="options"
 opa_fun_options() {
-    glb_run=0
-
-    declare opt
-    declare als
-    declare ret
+    declare opt als ret
 
     for als in "${!opa_als[@]}"; do
         opt="${opa_als[$als]}"
         ret="$ret --${opt//_/-}" && [ "$opt" != "$als" ] && ret="$ret -$als"
     done
 
-    echo "${ret:1}"
+    echo "${ret:1}"; return 0
 }
 
 #
 # Useage:
 #     dev --completion
-#     dev --completion <cmd-file>
+#     dev --completion <prj> <cmd-file>
 #
-opa_rem[completion]="List all command files or functions"
+opa_rem[completion]="List all project, command files or function files"
 opa_als[completion]="completion"
 opa_fun_completion() {
-    glb_run=0
-
-    declare ret
-    declare key
+    declare ret key
 
     if [[ $# -le 0 || -z "$1" ]]; then
         dev_cmd_files $glb_wkdir/cmd
     else
-        dev_load_files $1
+        dev_files $1
         for key in $(compgen -A function); do
             [ "${key:0:4}" == "cmd_" ] && ret="$ret ${key:4}"
         done
     fi
 
-    echo "${ret:1}"
+    echo "${ret:1}"; return 1
 }
 
 #
 # Useage:
-#     dev --deploy [user]
+#     dev --deploy <prj:user>
 #
 opa_rem[deploy]="Remote deployment"
 opa_als[deploy]="deploy"
 opa_fun_deploy() {
-    glb_run=0
+    [ -z "$1" ] && echo "Useage: dev --deploy <prj:user>" >&2 && return 1
 
-    declare cmd user host sudoer init_tar=$glb_wkdir/dev-init.tar
+    declare cmd user host sudoer init_tar=/tmp/dev-init.tar
 
     cmd="mkdir -m 700 -p \$HOME/.ssh &&"
     cmd="$cmd cat > \$HOME/.ssh/authorized_keys &&"
@@ -115,31 +99,33 @@ opa_fun_deploy() {
         dev_ssh $user@$host "\$HOME/dev-installer $glb_wkdir $sudoer"
     done
 
-    rm -f $init_tar
+    rm -f $init_tar; return 1
 }
+
 #
 # Useage:
-#     dev <prj> --init
+#     dev --init <prj>
 #
 opa_rem[init]="Create a new project directory structure"
 opa_als[init]="init"
 opa_fun_init() {
-    glb_run=0
+    [ -z "$1" ] || [ "$1" = "dev" ] && echo "Useage: dev --init <prj>" >&2 && return 1
 
-    [ -z "$glb_prj" ] || [ "$glb_prj" = "dev" ] && echo "Useage: dev <prj> --init" >&2 && return 1
-    [ -d $glb_wkdir/bin ] || [ -d $glb_wkdir/cmd ] && echo "Project $glb_prj exists" >&2 && return 1
+    declare prj="$1" wkdir="${cfg_projects[$1]}";
+    [ -z "$wkdir" ] && echo "Project config path error" >&2 && return 1
+    [ -d $wkdir/bin ] || [ -d $wkdir/cmd ] && echo "Project $prj exists" >&2 && return 1
 
     mkdir -p \
-        $glb_wkdir/bin \
-        $glb_wkdir/cmd \
-        $glb_wkdir/etc/cmd \
-        $glb_wkdir/lib \
-        $glb_wkdir/var/log \
-        $glb_wkdir/var/misc \
-        $glb_wkdir/var/pkg \
-        $glb_wkdir/var/tmp
+        $wkdir/bin \
+        $wkdir/cmd \
+        $wkdir/etc/cmd \
+        $wkdir/lib \
+        $wkdir/var/log \
+        $wkdir/var/misc \
+        $wkdir/var/pkg \
+        $wkdir/var/tmp
 
-    [ -f $glb_wkdir/lib/bootstrap ] || touch $glb_wkdir/lib/bootstrap
+    [ -f $wkdir/lib/bootstrap ] || touch $wkdir/lib/bootstrap; return 1
 }
 
 #
@@ -151,7 +137,7 @@ opa_rem[all]="Runs on all of the available nodes"
 opa_als[a]="all"
 opa_fun_all() {
     # 0: Local machine, 1: Specifies nodes, 2: Specifies group 3: All nodes
-    glb_run_level=3
+    glb_run_level=3; return 0
 }
 
 #
@@ -161,7 +147,7 @@ opa_fun_all() {
 opa_rem[daemon]="Run a command immune to hangups, with output to a non-tty"
 opa_als[daemon]="daemon"
 opa_fun_daemon() {
-    glb_run_daemon=1
+    glb_run_daemon=1; return 0
 }
 
 #
@@ -172,7 +158,7 @@ opa_fun_daemon() {
 opa_rem[sudo]="Execute a command as another user"
 opa_als[u]="sudo"
 opa_fun_sudo() {
-    glb_run_sudo=1
+    glb_run_sudo=1; return 0
 }
 
 #
@@ -182,10 +168,9 @@ opa_fun_sudo() {
 opa_rem[xtrace]="Print command traces before executing command"
 opa_als[xtrace]="xtrace"
 opa_fun_xtrace() {
-    set -o xtrace
-
     # trap 'echo "# $BASH_COMMAND"' DEBUG
 
     # Prints shell input lines as they are read
     # set -o verbose
+    set -o xtrace; return 0
 }
