Tee

diff --git a/bin/dev b/bin/dev
--- a/bin/dev
+++ b/bin/dev
@@ -181,7 +181,7 @@ dev_dnf() {
     # -4     Resolve to IPv4 addresses only.
     # --allowerasing
     #        Allow  erasing  of  installed  packages  to  resolve dependencies.
-    declare cmd="dnf -y --allowerasing -4 $@"
+    declare cmd="sudo dnf -y --allowerasing -4 $@"
     echo "$cmd" && $cmd
 }
 
@@ -255,8 +255,8 @@ dev_completion() {
 dev_deploy() {
     declare wkdir
 
-    [ -z "$glb_argv" ] && wkdir="$glb_wkdir" || wkdir="${cfg_projects[$glb_argv]}"
-    [ -z "$wkdir" ] && echo "Config error: cfg_projects[$prj], in $glb_base/etc/dev.conf" >&2 && return 1
+    [ -z "$glb_argv" ] || [ "$glb_argv" == "dev" ] && wkdir="$glb_wkdir" || wkdir="${cfg_projects[$glb_argv]}"
+    [ -z "$wkdir" ] && echo "Config error in $glb_base/etc/dev.conf" >&2 && return 1
     [ "${#glb_run_nodes[@]}" -le 0 ] && echo "Nodes is empty" >&2 && return 1
 
     declare cmd user host sudoer init_tar=/tmp/dev-init.tar
@@ -450,35 +450,29 @@ dev_exec_local() {
 #     dev_exec <host> <user> <command> <arguments>...
 #
 dev_exec() {
-    declare cmd log_err log_out
+    declare cmd log_out
     declare host="$1"; shift
     declare user="$1"; shift
     declare desc="[$user@$host $(date '+%Y-%m-%d %H:%M:%S')]"
 
     log_out="$glb_wkdir/var/log/$host.out"
-    log_err="$glb_wkdir/var/log/$host.err"
 
-    # $@ 2>&1 | tee $log_out
-    # ($@ | tee $log_out) 3>&1 1>&2 2>&3 | tee $log_err
     cmd="$@"
 
     if [ $glb_run_compact -eq 0 ]; then
-        echo "$desc" >>$log_out; echo "$desc" >>$log_err
-        echo "$cmd"; echo "$cmd" >>$log_out; echo "$cmd" >>$log_err
-        chmod a+wx $log_out $log_err
+        echo "$desc" >>$log_out
+        echo "$cmd"; echo "$cmd" >>$log_out
+        chmod a+wx $log_out
     fi
 
     [ $glb_run_dry -eq 1 ] && return 0
 
     if [ $glb_run_daemon -eq 1 ]; then
-        nohup $cmd >>$log_out 2>>$log_err &
+        nohup $cmd >>$log_out 2>&1 &
         echo "PID: $!"
     else
-        $cmd
-        # echo "$?"
+        $cmd 2>&1 | tee -a $log_out
     fi
-
-    # echo "out: $(< $log_out)"; echo "err: $(< $log_err)"
 }
 
 #
