\#!/bin/bash

diff --git a/lib/kernel b/lib/kernel
--- a/lib/kernel
+++ b/lib/kernel
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # Copyright 2016 The dev Authors. All rights reserved.
 # Use of this source code is governed by a BSD-style
 # license that can be found in the LICENSE file.
@@ -126,7 +126,7 @@ dev_load_files() {
     [ -f $wkdir/lib/bootstrap ] && . $wkdir/lib/bootstrap
     [ -f $wkdir/etc/dev.cmd/$cf.conf ] && . $wkdir/etc/dev.cmd/$cf.conf
     [ -f $wkdir/cmd/$cf.var ] && . $wkdir/cmd/$cf.var
-    [ ! -f $wkdir/cmd/$cf.sh ] && return 1 || . $wkdir/cmd/$cf.sh
+    [ ! -f $wkdir/cmd/$cf.bash ] && return 1 || . $wkdir/cmd/$cf.bash
 }
 
 #
@@ -136,8 +136,8 @@ dev_cmd_files() {
     for i in $(ls $1); do
         if [[ -d $1/$i ]]; then
             dev_cmd_files $1/$i $i/
-        elif [[ "${i: -3}" == ".sh" ]]; then
-            echo "$2${i:0:-3}"
+        elif [[ "${i: -5}" == ".bash" ]]; then
+            echo "$2${i:0:-5}"
         fi
     done
 }
@@ -203,7 +203,7 @@ dev_file() {
     fi
 
     if ! dev_load_files $glb_wkdir $1; then
-        echo "Command file not found: $glb_wkdir/cmd/$1.sh" >&2; return 1
+        echo "Command file not found: $glb_wkdir/cmd/$1.bash" >&2; return 1
     fi
 
     glb_file="$1"; return 0
